# Generated by Django 4.0.4 on 2023-11-06 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager', '0002_auto_20201113_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='year',
            field=models.PositiveSmallIntegerField(default=2023, validators=[django.core.validators.MaxValueValidator(2035), django.core.validators.MinValueValidator(2015)]),
        ),
    ]
